/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef BUCKET_STORE_MAPPING_H
#define BUCKET_STORE_MAPPING_H

#include "bucketupdater_types.h"

/* BucketStoreMapping service interface */
typedef struct _BucketStoreMappingIf BucketStoreMappingIf;  /* dummy object */

struct _BucketStoreMappingIfInterface
{
  GTypeInterface parent;

  gboolean (*get_mapping) (BucketStoreMappingIf *iface, GHashTable ** _return, const gchar * category, BucketStoreMappingException ** e, GError **error);
};
typedef struct _BucketStoreMappingIfInterface BucketStoreMappingIfInterface;

GType bucket_store_mapping_if_get_type (void);
#define TYPE_BUCKET_STORE_MAPPING_IF (bucket_store_mapping_if_get_type())
#define BUCKET_STORE_MAPPING_IF(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_BUCKET_STORE_MAPPING_IF, BucketStoreMappingIf))
#define IS_BUCKET_STORE_MAPPING_IF(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj, TYPE_BUCKET_STORE_MAPPING_IF))
#define BUCKET_STORE_MAPPING_IF_GET_INTERFACE(inst) (G_TYPE_INSTANCE_GET_INTERFACE ((inst), TYPE_BUCKET_STORE_MAPPING_IF, BucketStoreMappingIfInterface))

gboolean bucket_store_mapping_if_get_mapping (BucketStoreMappingIf *iface, GHashTable ** _return, const gchar * category, BucketStoreMappingException ** e, GError **error);

/* BucketStoreMapping service client */
struct _BucketStoreMappingClient
{
  GObject parent;

  ThriftProtocol *input_protocol;
  ThriftProtocol *output_protocol;
};
typedef struct _BucketStoreMappingClient BucketStoreMappingClient;

struct _BucketStoreMappingClientClass
{
  GObjectClass parent;
};
typedef struct _BucketStoreMappingClientClass BucketStoreMappingClientClass;

GType bucket_store_mapping_client_get_type (void);
#define TYPE_BUCKET_STORE_MAPPING_CLIENT (bucket_store_mapping_client_get_type())
#define BUCKET_STORE_MAPPING_CLIENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_BUCKET_STORE_MAPPING_CLIENT, BucketStoreMappingClient))
#define BUCKET_STORE_MAPPING_CLIENT_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), TYPE_BUCKET_STORE_MAPPING_CLIENT, BucketStoreMappingClientClass))
#define BUCKET_STORE_MAPPING_IS_CLIENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_BUCKET_STORE_MAPPING_CLIENT))
#define BUCKET_STORE_MAPPING_IS_CLIENT_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_BUCKET_STORE_MAPPING_CLIENT))
#define BUCKET_STORE_MAPPING_CLIENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_BUCKET_STORE_MAPPING_CLIENT, BucketStoreMappingClientClass))

gboolean bucket_store_mapping_client_get_mapping (BucketStoreMappingIf * iface, GHashTable ** _return, const gchar * category, BucketStoreMappingException ** e, GError ** error);
gboolean bucket_store_mapping_client_send_get_mapping (BucketStoreMappingIf * iface, const gchar * category, GError ** error);
gboolean bucket_store_mapping_client_recv_get_mapping (BucketStoreMappingIf * iface, GHashTable ** _return, BucketStoreMappingException ** e, GError ** error);

#endif /* BUCKET_STORE_MAPPING_H */
