/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef FB303_TYPES_H
#define FB303_TYPES_H

/* base includes */
#include <glib-object.h>
#include <thrift_struct.h>
#include <protocol/thrift_protocol.h>

/* custom thrift includes */

/* begin types */

enum _fb_status {
  FB_STATUS_DEAD = 0,
  FB_STATUS_STARTING = 1,
  FB_STATUS_ALIVE = 2,
  FB_STATUS_STOPPING = 3,
  FB_STATUS_STOPPED = 4,
  FB_STATUS_WARNING = 5
};
typedef enum _fb_status fb_status;

/* constants */

#endif /* FB303_TYPES_H */
